---
- name: Define PostgreSQL release version
  ansible.builtin.set_fact:
    postgresql_release: "{{ postgresql_version.split('.')[0] }}"

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Pre-installation system tasks
  import_tasks: system.yml

- name: OS-specific tasks
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Install PostgreSQL server
  ansible.builtin.package:
    name: "{{ postgresql_packages }}"
    state: present

- name: Initialize PostgreSQL instance
  import_tasks: initialize.yml

- name: Configure PostgreSQL instance
  import_tasks: configure.yml

- name: Manage PostgreSQL service
  import_tasks: service.yml
