---
- name: Disable PostgreSQL AppStream module
  ansible.builtin.copy:
    dest: /etc/dnf/modules.d/postgresql.module
    content: |
      [postgresql]
      name=postgresql
      stream=
      profiles=
      state=disabled
  when: ansible_distribution_major_version|int >= 8

- name: Add PostgreSQL 'common' RPM repository
  ansible.builtin.yum_repository:
    name: postgresql-common
    description: "PostgreSQL common RPMs for {{ ansible_distribution }} $releasever - $basearch"
    baseurl: "{{ postgresql_repo_common_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgresql_release }}"

- name: Add PostgreSQL {{ postgresql_release }} 'server' RPM repository
  ansible.builtin.yum_repository:
    name: "postgresql-{{ postgresql_release }}"
    description: "PostgreSQL {{ postgresql_release }} for {{ ansible_distribution }} $releasever - $basearch"
    baseurl: "{{ postgresql_repo_server_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgresql_release }}"
